### ISSUE TITLE
App issue locally after yarn dev command

### ISSUE THREAD

**Issue by dsuraj72** [aws-samples/amazon-chime-sdk-classroom-demo#21]
Hi Team,

After the completion of step 1(Option 2: Deploy from your local machine), i was trying to run the app locally with **yarn dev** command. Currently i'm facing couple of issues:

1. Getting below error with **yarn dev** command:
![Screenshot 2020-08-21 at 7 22 38 PM](https://user-images.githubusercontent.com/14140865/90902176-b44c3600-e3e9-11ea-8494-05cb9edaadf2.png)

2. Audio/Video not working locally (it works in application under release folder):
I'm was able to join as a Teacher/Student in app. & web socket seems to be work. Issue is with audio/video, unable to access them locally in app.

Versions:
MacOS - Catalina V10.15.4 (19E287)
node - v11.10.1

Pls. let me know if you need any other info.

Thanks.

**Comment by simmkyu** [comment]
<img width="1536" alt="Screen Shot 2020-08-28 at 4 19 38 PM" src="https://user-images.githubusercontent.com/36240708/91622154-ac8d1400-e94a-11ea-8429-a2f4864395f6.png">

In my macOS Catlina, I just removed `node_modules` folder, deployed the app (Step 1 in [Option 2](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo#option-2-deploy-from-your-local-machine)), and then ran `yarn dev`. I could execute the dev app without the `Error: Exited with code 9` error.

Versions:
macOS - Catalina V10.15.6 (19G2021)
Node - v12.16.3
NPM - 6.14.4

---

This classroom demo is using the `electron-react-boilerplate` project. In the following open issue, some users are having the same `Exited with code 9` error, but the cause is unknown.
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2535

`yarn dev` worked in a similar setup. Could you try deploying and running `yarn dev` in Node v12.16.3 and NPM 6.14.4?

**Comment by simmkyu** [comment]
> 2. Audio/Video not working locally (it works in application under release folder):
I'm was able to join as a Teacher/Student in app. & web socket seems to be work. Issue is with audio/video, unable to access them locally in app.

Have you allowed the microphone and camera permission before? When you open the dev app for the first time, the permission dialog would pop up.

<img src="https://user-images.githubusercontent.com/36240708/91622895-165aed00-e94e-11ea-82e5-dd8064e19619.png" width="320"></img>


You can also enable the permission in the macOS "Security & Privacy" settings. Make sure that "Terminal" and your app name in the release folder are in the list.

> "Terminal" is for the local demo app launched with `yarn dev`. I confirmed that audio calling didn't work when I disabled the Terminal checkbox. We'll add it to the doc.

<img width="600" alt="Screen Shot 2020-08-28 at 4 51 07 PM" src="https://user-images.githubusercontent.com/36240708/91623126-042d7e80-e94f-11ea-97f9-9cc179aa2980.png">
