### ISSUE TITLE
Apple Mac Store Submission Error

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-sdk-classroom-demo#27]
We are trying to submit the app in the Apple Mac store, but getting rejection with the following error:

Specifically, App still launches to no UI; user is unable to use the app.
Note: No main window appears on launch, menu and icon on Dock only.

Any Idea?

**Comment by simmkyu** [comment]
The classroom demo is built using the Electron React Boilerplate project.
- https://github.com/electron-react-boilerplate/electron-react-boilerplate

I couldn't find any rejection issue due to the "No main window appears on launch, menu and icon on Dock only." We haven't modified the initial launch behavior, except that we are changing the window size during screen sharing.

Recommend reviewing the following Electron submission guide and updating the "electron-react-boilerplate" and the Electron version:
https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide

Please reopen the issue if you need further assistance.

**Comment by vijayamin83** [comment]
Thank you for the sharing the detail, but I have built the MAS build from the steps mentioned in the above URL. 

Is there any way that we can test the MAS build before uploading to App Store?
