### ISSUE TITLE
Step 1 not working

### ISSUE THREAD

**Issue by shalonbd** [aws-samples/amazon-chime-sdk-classroom-demo#35]
Can't seem to get Option 2 deploy from local machine running

I'm running the script/deploy.js -r <region> -a <app name> -s <unique stack name> -b <unique bucket name> but I'm getting a windows script host error with error: invalid character at line:1 Char:1 with error code 800A03F6

**Comment by gayoso** [comment]
Hi, same happened to me. I believe it's because windows tries to run the script with a native Javascript interpreter instead of NodeJs. If you installed node correctly, try running "node script/deploy.js -r -a -s -b".

You will probably need to also change the line inside deploy.js "spawnOrFail('script/cloud9-resize.sh', []);" to "spawnOrFail('bash script/cloud9-resize.sh', []);". Or you can just comment it out since I believe it's only needed for Cloud9.

After this I had some errors creating buckets, so I ended trying the Option 1 with Cloud9 which worked right off the bat.

If you get further, you may need to dome some other modifications as I believe the code is prepared to run on ubuntu, not windows.

**Comment by RidipDe** [comment]
Just to confirm, can you please try with a new bucket name and stack name?

**Comment by vidya-mohan** [comment]
Please reactivate or cut a new issue if there are additional questions.
